
// (c) 2024 R.Hasaranga

#pragma once

// maximum bottle count is 8 and minimum is 3.
// maximum bar count is 4 and minimum is 2.

#define WS_EMPTY 0
#define WS_RED 1
#define WS_YELLOW 2
#define WS_ORANGE 3
#define WS_GREEN 4
#define WS_BLUE 5
#define WS_PURPLE 6
#define WS_BROWN 7

#define WATERSORT_LEVEL_COUNT 21

// level format: bottle count, bar count, colours from bottom to top

// levels from https://poki.com/en/g/water-color-sort

const uint8_t watersort_level_3[] PROGMEM = {
	4, 4,
	WS_RED, WS_BLUE, WS_YELLOW, WS_EMPTY,
	WS_BLUE, WS_BLUE, WS_RED, WS_EMPTY,
	WS_RED, WS_RED, WS_YELLOW, WS_EMPTY,
	WS_YELLOW, WS_YELLOW, WS_BLUE, WS_EMPTY
};

const uint8_t watersort_level_4[] PROGMEM = {
	5, 4,
	WS_GREEN, WS_BLUE, WS_EMPTY, WS_EMPTY,
	WS_RED, WS_RED, WS_GREEN, WS_EMPTY,
	WS_BLUE, WS_RED, WS_GREEN, WS_EMPTY,
	WS_GREEN, WS_RED, WS_EMPTY, WS_EMPTY,
	WS_BLUE, WS_BLUE, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_5[] PROGMEM = {
	7, 4,
	WS_YELLOW, WS_YELLOW, WS_RED, WS_GREEN,
	WS_ORANGE, WS_BLUE, WS_RED, WS_GREEN,
	WS_BLUE, WS_RED, WS_ORANGE, WS_RED,
	WS_ORANGE, WS_YELLOW, WS_GREEN, WS_BLUE,
	WS_YELLOW, WS_ORANGE, WS_GREEN, WS_BLUE,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_6[] PROGMEM = {
	7, 4,
	WS_BLUE, WS_BLUE, WS_BLUE, WS_ORANGE,
	WS_BLUE, WS_GREEN, WS_YELLOW, WS_GREEN,
	WS_GREEN, WS_YELLOW, WS_ORANGE, WS_YELLOW,
	WS_YELLOW, WS_ORANGE, WS_GREEN, WS_RED,
	WS_ORANGE, WS_RED, WS_RED, WS_RED,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_7[] PROGMEM = {
	7, 4,
	WS_ORANGE, WS_GREEN, WS_ORANGE, WS_YELLOW,
	WS_ORANGE, WS_YELLOW, WS_GREEN, WS_RED,
	WS_YELLOW, WS_YELLOW, WS_RED, WS_BLUE,
	WS_RED, WS_RED, WS_GREEN, WS_BLUE,
	WS_ORANGE, WS_BLUE, WS_GREEN, WS_BLUE,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_8[] PROGMEM = {
	7, 4,
	WS_YELLOW, WS_GREEN, WS_ORANGE, WS_RED,
	WS_YELLOW, WS_ORANGE, WS_GREEN, WS_BLUE,
	WS_BLUE, WS_ORANGE, WS_YELLOW, WS_ORANGE,
	WS_RED, WS_BLUE, WS_BLUE, WS_RED,
	WS_GREEN, WS_RED, WS_GREEN, WS_YELLOW,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_9[] PROGMEM = {
	7, 4,
	WS_GREEN, WS_YELLOW, WS_BLUE, WS_BLUE,
	WS_ORANGE, WS_RED, WS_GREEN, WS_BLUE,
	WS_RED, WS_YELLOW, WS_YELLOW, WS_ORANGE,
	WS_RED, WS_GREEN, WS_GREEN, WS_YELLOW,
	WS_ORANGE, WS_RED, WS_BLUE, WS_ORANGE,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_10[] PROGMEM = {
	7, 4,
	WS_RED, WS_GREEN, WS_YELLOW, WS_ORANGE,
	WS_BLUE, WS_ORANGE, WS_RED, WS_ORANGE,
	WS_RED, WS_BLUE, WS_YELLOW, WS_BLUE,
	WS_GREEN, WS_YELLOW, WS_BLUE, WS_GREEN,
	WS_RED, WS_GREEN, WS_ORANGE, WS_YELLOW,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_11[] PROGMEM = {
	7, 4,
	WS_YELLOW, WS_YELLOW, WS_ORANGE, WS_BLUE,
	WS_GREEN, WS_GREEN, WS_ORANGE, WS_EMPTY,
	WS_PURPLE, WS_PURPLE, WS_GREEN, WS_BLUE,
	WS_BLUE, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_RED, WS_RED, WS_ORANGE, WS_RED,
	WS_ORANGE, WS_YELLOW, WS_YELLOW, WS_BLUE,
	WS_PURPLE, WS_PURPLE, WS_RED, WS_GREEN
};

const uint8_t watersort_level_12[] PROGMEM = {
	7, 4,
	WS_YELLOW, WS_PURPLE, WS_BLUE, WS_EMPTY,
	WS_GREEN, WS_GREEN, WS_RED, WS_PURPLE,
	WS_BLUE, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_ORANGE, WS_RED, WS_GREEN, WS_YELLOW,
	WS_RED, WS_RED, WS_ORANGE, WS_YELLOW,
	WS_ORANGE, WS_ORANGE, WS_GREEN, WS_YELLOW,
	WS_PURPLE, WS_BLUE, WS_BLUE, WS_PURPLE
};

const uint8_t watersort_level_13[] PROGMEM = {
	5, 4,
	WS_BLUE, WS_PURPLE, WS_GREEN, WS_YELLOW,
	WS_GREEN, WS_PURPLE, WS_YELLOW, WS_EMPTY,
	WS_YELLOW, WS_PURPLE, WS_GREEN, WS_EMPTY,
	WS_PURPLE, WS_BLUE, WS_EMPTY, WS_EMPTY,
	WS_GREEN, WS_YELLOW, WS_BLUE, WS_BLUE
};

const uint8_t watersort_level_14[] PROGMEM = {
	7, 4,
	WS_RED, WS_ORANGE, WS_RED, WS_PURPLE,
	WS_ORANGE, WS_YELLOW, WS_RED, WS_PURPLE,
	WS_BLUE, WS_ORANGE, WS_RED, WS_YELLOW,
	WS_ORANGE, WS_BLUE, WS_PURPLE, WS_BLUE,
	WS_BLUE, WS_PURPLE, WS_YELLOW, WS_YELLOW,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_15[] PROGMEM = {
	7, 4,
	WS_RED, WS_RED, WS_GREEN, WS_BLUE,
	WS_PURPLE, WS_PURPLE, WS_YELLOW, WS_PURPLE,
	WS_ORANGE, WS_ORANGE, WS_EMPTY, WS_EMPTY,
	WS_YELLOW, WS_BLUE, WS_ORANGE, WS_EMPTY,
	WS_BLUE, WS_YELLOW, WS_BLUE, WS_EMPTY,
	WS_GREEN, WS_GREEN, WS_PURPLE, WS_GREEN,
	WS_RED, WS_RED, WS_YELLOW, WS_ORANGE
};

const uint8_t watersort_level_16[] PROGMEM = {
	7, 4,
	WS_YELLOW, WS_GREEN, WS_RED, WS_GREEN,
	WS_RED, WS_RED, WS_YELLOW, WS_BLUE,
	WS_PURPLE, WS_BLUE, WS_PURPLE, WS_YELLOW,
	WS_PURPLE, WS_BLUE, WS_RED, WS_PURPLE,
	WS_BLUE, WS_GREEN, WS_GREEN, WS_YELLOW,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_17[] PROGMEM = {
	8, 4,
	WS_BLUE, WS_GREEN, WS_GREEN, WS_BROWN,
	WS_RED, WS_RED, WS_PURPLE, WS_BROWN,
	WS_PURPLE, WS_PURPLE, WS_ORANGE, WS_YELLOW,
	WS_BROWN, WS_BROWN, WS_PURPLE, WS_YELLOW,
	WS_GREEN, WS_GREEN, WS_RED, WS_YELLOW,
	WS_ORANGE, WS_BLUE, WS_RED, WS_ORANGE,
	WS_YELLOW, WS_BLUE, WS_EMPTY, WS_EMPTY,
	WS_ORANGE, WS_BLUE, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_18[] PROGMEM = {
	8, 4,
	WS_BLUE, WS_BLUE, WS_BROWN, WS_PURPLE,
	WS_RED, WS_BROWN, WS_PURPLE, WS_ORANGE,
	WS_PURPLE, WS_PURPLE, WS_RED, WS_BLUE,
	WS_BROWN, WS_BROWN, WS_ORANGE, WS_GREEN,
	WS_GREEN, WS_YELLOW, WS_RED, WS_GREEN,
	WS_ORANGE, WS_ORANGE, WS_YELLOW, WS_EMPTY,
	WS_YELLOW, WS_YELLOW, WS_GREEN, WS_BLUE,
	WS_RED, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_19[] PROGMEM = {
	7, 4,
	WS_PURPLE, WS_PURPLE, WS_RED, WS_ORANGE,
	WS_PURPLE, WS_BLUE, WS_BLUE, WS_GREEN,
	WS_ORANGE, WS_BLUE, WS_RED, WS_GREEN,
	WS_ORANGE, WS_PURPLE, WS_RED, WS_GREEN,
	WS_GREEN, WS_ORANGE, WS_BLUE, WS_RED,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_20[] PROGMEM = {
	7, 4,
	WS_BLUE, WS_PURPLE, WS_BROWN, WS_RED,
	WS_RED, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_BROWN, WS_PURPLE, WS_RED, WS_EMPTY,
	WS_YELLOW, WS_YELLOW, WS_BLUE, WS_GREEN,
	WS_PURPLE, WS_GREEN, WS_BLUE, WS_PURPLE,
	WS_GREEN, WS_GREEN, WS_BROWN, WS_RED,
	WS_YELLOW, WS_YELLOW, WS_BLUE, WS_BROWN
};

const uint8_t watersort_level_21[] PROGMEM = {
	7, 4,
	WS_PURPLE, WS_BROWN, WS_YELLOW, WS_BROWN,
	WS_YELLOW, WS_PURPLE, WS_BROWN, WS_GREEN,
	WS_GREEN, WS_GREEN, WS_YELLOW, WS_RED,
	WS_BROWN, WS_YELLOW, WS_RED, WS_PURPLE,
	WS_PURPLE, WS_RED, WS_RED, WS_GREEN,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_EMPTY, WS_EMPTY, WS_EMPTY, WS_EMPTY
};

const uint8_t watersort_level_22[] PROGMEM = {
	6, 4,
	WS_PURPLE, WS_PURPLE, WS_GREEN, WS_BLUE,
	WS_BROWN, WS_BROWN, WS_GREEN, WS_BROWN,
	WS_GREEN, WS_RED, WS_BLUE, WS_RED,
	WS_BLUE, WS_BROWN, WS_RED, WS_EMPTY,
	WS_RED, WS_EMPTY, WS_EMPTY, WS_EMPTY,
	WS_PURPLE, WS_PURPLE, WS_BLUE, WS_GREEN
};

// 32 level
const uint8_t watersort_level_23[] PROGMEM = {
	6, 4,
	WS_PURPLE, WS_PURPLE, WS_RED, WS_BLUE,
	WS_BROWN, WS_BROWN, WS_GREEN, WS_EMPTY,
	WS_GREEN, WS_BLUE, WS_PURPLE, WS_EMPTY,
	WS_BLUE, WS_BLUE, WS_RED, WS_EMPTY,
	WS_RED, WS_BROWN, WS_BROWN, WS_GREEN,
	WS_GREEN, WS_PURPLE, WS_RED, WS_EMPTY
};

const uint8_t* watersort_levels[] = {
watersort_level_3, watersort_level_4, watersort_level_5, watersort_level_6,
watersort_level_7, watersort_level_8,watersort_level_9,  watersort_level_10,
watersort_level_11, watersort_level_12, watersort_level_13, watersort_level_14,
watersort_level_15, watersort_level_16, watersort_level_17, watersort_level_18,
watersort_level_19, watersort_level_20, watersort_level_21, watersort_level_22,
watersort_level_23};